# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 764668a2f25b151a667dad41df275dfd736a5b960f292aa8887c621b1fb72cc34f17175a5811079d1be27e871f21d4b4bd2046fdf290db4465fbe42f1ff4fbea

test:
  secret_key_base: 789d436bf4630d68b7f8c595f326d14608a99cf27a493a68c7ccf558a64ed66f960ca44ec978ed5e86d3e458f5274c59ba941a14755a59675b89b5ec90ec0210

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
